Django_project/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
path("<int:id>", views.index, name='index'),
path("", views.home, name='home')
]

Django_project/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),

    
]

Django_project/main/models.py
from django.db import models

class ToDoList(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Item(models.Model):
    ToDoList = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    text = models.TextField(max_length=300)
    complete = models.BooleanField()

    def __str__(self):
        return self.text

Django_project/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import ToDoList, Item

def index(response, id):
    ls = ToDoList.objects.get(id=id)
    return render(response, "main/list.html", {"ls":ls})

def home(response):
    return render(response, "main/home.html", {})

Django_project/main/templates/main/base.html
<html>
<head>
    <title>{% block title%}Frugo's Site{% endblock%}</title>
</head>

<body>
    <div id="content", name="content">
        {% block content %}
        <h1>Hello</h1>
        {% endblock %}
    </div>

</body>
</html>

Django_project/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<h1>Home Page</h1>
{% endblock %}

Django_project/main/templates/main/list.html
{% extends "main/base.html" %}
{% block title %}View List{% endblock %}

{% block content%}
    <h1>{{ls.name}}</h1>
    <ul>
        {% for item in ls.item_set.all %}
            {% if item.complete == False %}
                <li>{{item.text}}</li>    
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}